openapi: 3.0.0
info:
  title: Trello Connector
  version: 1.0.0

servers:
  - url: https://dp-trello-v41.vercel.app   # update if you use a different host

paths:
  /mcp/boards:
    get:
      summary: List Trello boards
      operationId: listBoards
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  boards:
                    type: array
                    items: { type: object }

  /mcp/boards/{boardId}/cards:
    get:
      summary: List cards on a board
      operationId: listCardsOnBoard
      parameters:
        - in: path
          name: boardId
          required: true
          schema: { type: string }
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  cards:
                    type: array
                    items: { type: object }
